### ISSUE TITLE
Release 2.2.0 doesn't work

### ISSUE THREAD

**Issue by yiikou** [smartshark/labelSHARK#6]
Hi, I tried out release 2.2.0 and 2.1.0. 2.1.0 works while 2.2.0 fails.

For 2.1.0, i receive a bunch of same warning:`unknown ITS type for ITS url https://api.github.com/repos/junit-team/junit4/issues for feature add labels` without issue id. I'm not sure is it a normal output? 

And by checking the result in visualSHARK 
![image](https://user-images.githubusercontent.com/6872777/98701847-b7e7bd00-2347-11eb-8247-bde87061e214.png)
I haven't observed a commit that is labeled. I can't help expecting that the new FastText based classification feature will improve it.

However, when I install it via serverSHARK (I confirmed the installation is completed by checking the worker log) and execute the plugin, I received this:
```
executing: /srv/www/serverSHARK/plugin_installations/labelSHARK_2.2.0/execute.sh /srv/www/serverSHARK/plugin_installations/labelSHARK_2.2.0 root CHANGEME smartshark localhost 27017 smartshark None None junit4 all  ... finished in 1.14372s [ERROR]
Traceback (most recent call last):
  File "/srv/www/serverSHARK/plugin_installations/labelSHARK_2.2.0/smartshark_plugin.py", line 108, in <module>
    main(parser.parse_args())
  File "/srv/www/serverSHARK/plugin_installations/labelSHARK_2.2.0/smartshark_plugin.py", line 73, in main
    __import__('approaches.{}'.format(app[:-3]))
  File "/srv/www/serverSHARK/plugin_installations/labelSHARK_2.2.0/approaches/issuefasttext.py", line 3, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
```
I tried to instal, uninstall pandas, but that doesn't help.

Do you also met this situation before? Or it just my local env problem.

**Comment by atrautsch** [comment]
Hm 2.2.0 maybe problematic because I had to do some patching for our HPC system.
I will try to reproduce this tomorrow.

The plugins use the user python directory. You would have to install pandas with --user and for the correct python version which may be 3.5 or 3.6.  The errors are probably from the feature addition, if Jira is used it maps some issue types to feature addition while it is not implemented for github issues. The fasttext feature only adds one specific label which uses a fasttext classifier to determine if an issue is a bug or another type (e.g., feature addition) and labels the commit accordingly.

**Comment by yiikou** [comment]
I will try with jira issue first. And weird, pandas is in the setup.py and it supposed to be installed already.

**Comment by atrautsch** [comment]
I just updated the labelSHARK and split of some code for our HPC system. It should now work in non-HPC mode on your serverSHARK out of the box.

**Comment by yiikou** [comment]
Hi, I have a follow up question towards the fasttext feature:
> The fasttext feature only adds one specific label which uses a fasttext classifier to determine if an issue is a bug or another type (e.g., feature addition) and labels the commit accordingly.

Given the description of changeSHARK: A library which is able to classify bugfixes using ChangeDistiller. Does it mean that the fasttext feature is duplicated with changeSHARK?

Thank you.

**Comment by atrautsch** [comment]
No, it loads the issues linked to the commit and runs them through a prediction model from "On the Feasibility of Automated Prediction of Bug and Non-Bug Issues" (https://arxiv.org/abs/2003.05357). The idea is that we can not manually label all issues as being a real bug or just a feature request, therefore we use this automatic approach.

**Comment by yiikou** [comment]
So labelSHARK 1) label bug-fixing issues, and 2) further label bug-fixing commit (as a "complementary" to changeSHARK in terms of commit labeling)?

**Comment by sherbold** [comment]
1) The task of the labelSHARK is to assign labels to commits based on other data in the data base. This data could be the commit message, linked issues, the hunks of the code changes, or any other data. 

2) The changeSHARK works directly on the (Java) source code and determines which type of changes are applied to the file and stores that in the commit_changes table. The changeSHARK does this for all code changes and does not care about bug fixes. Theoretically, we could compute labels based on the detected changes by the changeSHARK in the labelSHARK, e.g., to append a "interface_change" label to the commit.
